spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql-spring
    username: spring_prod_user
    password: emre
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: off